      <li><strong><em>Tous les transparents</em></strong> en <a href="article.ocaml.pdf">PDF</a> (29 pages, 245574 bytes).</li>
      <li><strong>Pr&eacute;sentation de mini-ML</strong> 
en <a href="introduction.pdf">PDF</a> (11 pages, 63213 bytes).</li>
      <li><strong>Variables, syntaxe abstraite et environnement</strong> 
en <a href="syntax.pdf">PDF</a> (10 pages, 58890 bytes).</li>
      <li><strong>&Eacute;valuation des programmes mini-ML</strong> 
en <a href="execution.pdf">PDF</a> (15 pages, 81258 bytes).</li>
      <li><strong>Extensions de mini-ML</strong> 
en <a href="extensions.pdf">PDF</a> (11 pages, 65713 bytes).</li>
      <li><strong>Types</strong> 
en <a href="types.pdf">PDF</a> (9 pages, 60633 bytes).</li>
      <li><strong>Variantes et filtrage de motifs</strong> 
en <a href="matching.pdf">PDF</a> (10 pages, 67974 bytes).</li>
      <li><strong>Listes</strong> 
en <a href="lists.pdf">PDF</a> (3 pages, 26877 bytes).</li>
      <li><strong>Exceptions</strong> 
en <a href="exceptions.pdf">PDF</a> (4 pages, 50158 bytes).</li>
