      <li><strong><em>All the slides in one file</em></strong> in <a href="article.concepts.pdf">PDF</a> (31 pages, 227702 bytes).</li>
      <li><strong>Introduction</strong> 
in <a href="introduction.pdf">PDF</a> (2 pages, 18298 bytes).</li>
      <li><strong>Fundamental concepts</strong> 
in <a href="calculator.pdf">PDF</a> (27 pages, 85383 bytes).</li>
      <li><strong>Boolean expressions</strong> 
in <a href="booleans.pdf">PDF</a> (17 pages, 65942 bytes).</li>
      <li><strong>Stacks</strong> 
in <a href="stacks.pdf">PDF</a> (24 pages, 75495 bytes).</li>
      <li><strong>Queues</strong> 
in <a href="queues.pdf">PDF</a> (2 pages, 22132 bytes).</li>
      <li><strong>Trees and their traversals</strong> 
in <a href="trees.pdf">PDF</a> (14 pages, 66933 bytes).</li>
