      <li><strong><em>Tous les transparents</em></strong> en <a href="article.comp.pdf">PDF</a> (55 pages, 521235 bytes).</li>
      <li><strong>Introduction</strong> 
en <a href="introduction.pdf">PDF</a> (11 pages, 70620 bytes).</li>
      <li><strong>S&eacute;mantique formelle</strong> 
en <a href="semantics.pdf">PDF</a> (86 pages, 296676 bytes).</li>
      <li><strong>Analyse lexicale</strong> 
en <a href="lexing.pdf">PDF</a> (31 pages, 154722 bytes).</li>
      <li><strong>Typage statique</strong> 
en <a href="typing.pdf">PDF</a> (25 pages, 121467 bytes).</li>
