      <li><strong><em>All the slides in one file</em></strong> in <a href="article.ir.pdf">PDF</a> (62 pages, 487597 bytes).</li>
      <li><strong>Foreword</strong> 
in <a href="foreword.pdf">PDF</a> (3 pages, 19252 bytes).</li>
      <li><strong>Basic definitions</strong> 
in <a href="basics.pdf">PDF</a> (6 pages, 33684 bytes).</li>
      <li><strong>A naive algorithm for text searching</strong> 
in <a href="naive.pdf">PDF</a> (3 pages, 28246 bytes).</li>
      <li><strong>The Morris-Pratt algorithm</strong> 
in <a href="morris-pratt.pdf">PDF</a> (38 pages, 107567 bytes).</li>
      <li><strong>The Knuth-Morris-Pratt algorithm</strong> 
in <a href="knuth-morris-pratt.pdf">PDF</a> (27 pages, 85332 bytes).</li>
      <li><strong>Deterministic Finite Automata</strong> 
in <a href="dfa.pdf">PDF</a> (25 pages, 82757 bytes).</li>
      <li><strong>Non-deterministic Finite Automata</strong> 
in <a href="nfa.pdf">PDF</a> (6 pages, 42460 bytes).</li>
      <li><strong>The subset construction</strong> 
in <a href="subset.pdf">PDF</a> (28 pages, 108799 bytes).</li>
      <li><strong>Epsilon Non-deterministic Finite Automata (e-NFA)</strong> 
in <a href="enfa.pdf">PDF</a> (33 pages, 114200 bytes).</li>
