      <li><strong><em>All the slides in one file</em></strong> in <a href="article.networks.pdf">PDF</a> (84 pages, 1419569 bytes).</li>
      <li><strong>Introduction</strong> 
in <a href="introduction.pdf">PDF</a> (14 pages, 114301 bytes).</li>
      <li><strong>The network edge</strong> 
in <a href="network_edge.pdf">PDF</a> (6 pages, 69314 bytes).</li>
      <li><strong>The network core</strong> 
in <a href="network_core.pdf">PDF</a> (32 pages, 259160 bytes).</li>
      <li><strong>The network access and physical media</strong> 
in <a href="network_access.pdf">PDF</a> (12 pages, 110538 bytes).</li>
      <li><strong>ISPs and internet backbones</strong> 
in <a href="isp.pdf">PDF</a> (4 pages, 49826 bytes).</li>
      <li><strong>Delay and loss in packet-switched networks</strong> 
in <a href="delay_loss.pdf">PDF</a> (17 pages, 87396 bytes).</li>
      <li><strong>Protocol layers and their service models</strong> 
in <a href="services.pdf">PDF</a> (19 pages, 148031 bytes).</li>
      <li><strong>Principle of application layer protocols</strong> 
in <a href="application.pdf">PDF</a> (16 pages, 231719 bytes).</li>
      <li><strong>The web and HTTP</strong> 
in <a href="http.pdf">PDF</a> (36 pages, 182496 bytes).</li>
      <li><strong>File transfer with FTP</strong> 
in <a href="ftp.pdf">PDF</a> (9 pages, 64907 bytes).</li>
      <li><strong>Mail in the Internet (SMTP, MIME, POP3, IMAP, HTTP)</strong> 
in <a href="mail.pdf">PDF</a> (36 pages, 189638 bytes).</li>
      <li><strong>The Internet's directory service (DNS)</strong> 
in <a href="dns.pdf">PDF</a> (25 pages, 183129 bytes).</li>
