      <li><strong><em>All the slides in one file</em></strong> in <a href="article.algspec.pdf">PDF</a> (36 pages, 255924 bytes).</li>
      <li><strong>Algebraic specification of booleans</strong> 
in <a href="booleans.pdf">PDF</a> (6 pages, 38476 bytes).</li>
      <li><strong>Rewrite systems</strong> 
in <a href="rewrite.pdf">PDF</a> (12 pages, 56600 bytes).</li>
      <li><strong>Algebraic specification of stacks</strong> 
in <a href="stacks.pdf">PDF</a> (21 pages, 79733 bytes).</li>
      <li><strong>Algebraic specification of queues</strong> 
in <a href="queues.pdf">PDF</a> (3 pages, 29876 bytes).</li>
      <li><strong>Trees and their classic traversals</strong> 
in <a href="trees.pdf">PDF</a> (26 pages, 100175 bytes).</li>
      <li><strong>Search algorithms based on stacks, queues and trees</strong> 
in <a href="search.pdf">PDF</a> (26 pages, 87115 bytes).</li>
