      <li><strong><em>All the slides in one file</em></strong> in <a href="article.erlang.pdf">PDF</a> (27 pages, 167146 bytes).</li>
      <li><strong>Rationale</strong> 
in <a href="rationale.pdf">PDF</a> (6 pages, 31285 bytes).</li>
      <li><strong>Introduction</strong> 
in <a href="introduction.pdf">PDF</a> (20 pages, 71763 bytes).</li>
      <li><strong>Lexicon</strong> 
in <a href="lexis.pdf">PDF</a> (14 pages, 53937 bytes).</li>
      <li><strong>Matching terms</strong> 
in <a href="matching.pdf">PDF</a> (23 pages, 67450 bytes).</li>
      <li><strong>Functions</strong> 
in <a href="functions.pdf">PDF</a> (4 pages, 24104 bytes).</li>
