      <li><strong><em>All the slides in one file</em></strong> in <a href="article.xml.pdf">PDF</a> (66 pages, 449059 bytes).</li>
      <li><strong>XML</strong> 
in <a href="xml_intro.pdf">PDF</a> (61 pages, 171866 bytes).</li>
      <li><strong>XHTML</strong> 
in <a href="xhtml.pdf">PDF</a> (19 pages, 66643 bytes).</li>
      <li><strong>DTD</strong> 
in <a href="dtd.pdf">PDF</a> (9 pages, 44397 bytes).</li>
      <li><strong>XSLT</strong> 
in <a href="xslt.pdf">PDF</a> (98 pages, 226708 bytes).</li>
