      <li><strong><em>All the slides in one file</em></strong> in <a href="article.compilers.pdf">PDF</a> (80 pages, 570598 bytes).</li>
      <li><strong>Overview of the compilation chain</strong> 
in <a href="overview.pdf">PDF</a> (39 pages, 124661 bytes).</li>
      <li><strong>Token specification</strong> 
in <a href="token_spec.pdf">PDF</a> (15 pages, 73136 bytes).</li>
      <li><strong>Regular expressions</strong> 
in <a href="regexp.pdf">PDF</a> (12 pages, 61734 bytes).</li>
      <li><strong>Lex, a tool for building lexers</strong> 
in <a href="lex.pdf">PDF</a> (19 pages, 67648 bytes).</li>
      <li><strong>Transition diagrams and regular expressions</strong> 
in <a href="token_recog.pdf">PDF</a> (40 pages, 137846 bytes).</li>
      <li><strong>Deterministic Finite Automata (DFA)</strong> 
in <a href="dfa.pdf">PDF</a> (14 pages, 63847 bytes).</li>
      <li><strong>Non-deterministic Finite Automata (NFA)</strong> 
in <a href="nfa.pdf">PDF</a> (6 pages, 51498 bytes).</li>
      <li><strong>The subset construction</strong> 
in <a href="subset.pdf">PDF</a> (27 pages, 118984 bytes).</li>
      <li><strong>Non-deterministic Finite Automata with epsilon-transitions (e-NFA)</strong> 
in <a href="enfa.pdf">PDF</a> (27 pages, 108971 bytes).</li>
      <li><strong>From regular expressions to e-NFAs</strong> 
in <a href="re_to_enfa.pdf">PDF</a> (8 pages, 46449 bytes).</li>
